### ISSUE TITLE
Problem of getting dataset

### ISSUE THREAD

**Issue by SeanSiyang** [pvnieo/DPFM#5]
Where can I get the datasets I need for training？
Can you provide the download link of the dataset?
Thx!!

**Comment by pvnieo** [comment]
Hi,

The links are provided in the readme. You can find them in [here](https://github.com/pvnieo/cp2p-pfarm-benchmark).

**Comment by SeanSiyang** [comment]
> Hi,
> 
> The links are provided in the readme. You can find them in [here](https://github.com/pvnieo/cp2p-pfarm-benchmark).

Sorry, my expression is wrong，I mean, where can i get the shrec_partial dataset?

**Comment by pvnieo** [comment]
Hi @immensitySea 

I just added SHREC16 to other repo, you can find it there.

Have a nice day!
