### ISSUE TITLE
Question about Shrec'16 Dataset

### ISSUE THREAD

**Issue by SeanSiyang** [pvnieo/DPFM#6]
Hi, Happy New Year!!! 
I have a question about the use of Shrec'16 Dataset.

I download the Dataset here: https://www.dais.unive.it/~shrec2016/dataset.php
There are three contents available for download, and I downloaded the first one:
`Partial datasets with ground truth correspondences (~200 shapes) `
`Test code to load and show ground-truth maps between shapes`
`The evaluation cuts (200 shapes) and holes (200 shapes) databases`

 I don't know if I downloaded it correctly.

When I unzip the downloaded file, I found it has three folders, "cuts", "holes", "null", and the label correspondence files is ".baryc_gt" as suffix.

In the documentation I found the following description:
```Ground-truth is provided for each deformed shape as a ASCII file with baryc_gt (baryc_gt_sym for the symmetric ground-truth) extension. Each row contains the triangle index and the barycentric weight of the corresponding point of the relative shape in canonical pose.```

However, in the code implementation such as "shrec_partial_dataset.py", and the implementation of the "ShrecPartialDataset" class, i found the label correspondence, and the code about read ground truth file is something about the file which is ".map" as suffix, this is different from the label file in Shrec'16 I downloaded.

My question is how do I convert files from '.baryc_gt' to '.map' ?

Thank you for your reply and help, have a nice day~~~

**Comment by pvnieo** [comment]
Hi,

for each vertex on the source shape, you choose the vertex with the highest barycentric coordinate on the target shape!
