### ISSUE TITLE
How to use functional map.

### ISSUE THREAD

**Issue by JarvisLee0423** [pvnieo/DPFM#7]
Hi, I have read your paper and viewed your codes. I want to know after getting the functional map between shape A and B, how can I use  the it to transform the shape A to B? Is there any possible to convert the functional map to the point-to-point correspondence? I see the C_gt is generated by using the points correspondence map from the training dataset, however, if we only have the functional map, how can I recover the points correspondence map?

**Comment by pvnieo** [comment]
see here: https://github.com/nmwsharp/diffusion-net/blob/b1019b049597711d10259ce28250f7dfc4335a2b/experiments/functional_correspondence/functional_correspondence.py#L195
